// <auto-generated />
using System;
using Knowz.SelfHosted.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Knowz.SelfHosted.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SelfHostedDbContext))]
    [Migration("20260902023226_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeTags", b =>
                {
                    b.Property<Guid>("KnowledgeItemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("KnowledgeItemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("KnowledgeTags");
                });

            modelBuilder.Entity("Knowz.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("TenantId", "EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Knowz.Core.Entities.ContentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingVectorJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsContextualEmbedding")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId", "ContentHash");

                    b.HasIndex("KnowledgeId", "Position");

                    b.HasIndex("TenantId", "KnowledgeId");

                    b.ToTable("ContentChunks");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Knowz.Core.Entities.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("FileRecordId");

                    b.HasIndex("KnowledgeId");

                    b.HasIndex("TenantId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("Knowz.Core.Entities.FileRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentAIProvider")
                        .HasColumnType("text");

                    b.Property<bool>("BlobMigrationPending")
                        .HasColumnType("boolean");

                    b.Property<string>("BlobUri")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LayoutDataJson")
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TextExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TextExtractionError")
                        .HasColumnType("text");

                    b.Property<int>("TextExtractionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TranscriptionText")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VisionAnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisionDescription")
                        .HasColumnType("text");

                    b.Property<string>("VisionExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("VisionObjectsJson")
                        .HasColumnType("text");

                    b.Property<string>("VisionTagsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("FileRecords");
                });

            modelBuilder.Entity("Knowz.Core.Entities.GitRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("CommitHistoryDepth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FilePatterns")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastCommitHistorySyncSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncCommitSha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TrackCommitHistory")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VaultId")
                        .IsUnique();

                    b.ToTable("GitRepositories");
                });

            modelBuilder.Entity("Knowz.Core.Entities.InboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedByUserId", "CreatedAt")
                        .HasDatabaseName("IX_InboxItems_TenantId_CreatedByUserId_CreatedAt");

                    b.ToTable("InboxItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BriefSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("SummaryRefinementGuidance")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TopicId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.HasIndex("TenantId", "CreatedByUserId");

                    b.HasIndex("TenantId", "FilePath");

                    b.HasIndex("TenantId", "Title");

                    b.HasIndex("TenantId", "Type");

                    b.ToTable("KnowledgeItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<string>("Sentiment")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "KnowledgeId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeEvent", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("KnowledgeId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("KnowledgeEvents");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeLocation", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.HasKey("KnowledgeId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("KnowledgeLocations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgePerson", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<double?>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Mentions")
                        .HasColumnType("integer");

                    b.Property<string>("RelationshipContext")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("KnowledgeId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("KnowledgePersons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAutoDetected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceKnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetKnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("SourceKnowledgeId", "RelationshipType")
                        .HasDatabaseName("IX_KnowledgeRelationships_Source_Type");

                    b.HasIndex("TargetKnowledgeId", "RelationshipType")
                        .HasDatabaseName("IX_KnowledgeRelationships_Target_Type");

                    b.HasIndex("TenantId", "SourceKnowledgeId", "TargetKnowledgeId")
                        .IsUnique()
                        .HasDatabaseName("IX_KnowledgeRelationships_Tenant_Source_Target");

                    b.ToTable("KnowledgeRelationships");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeVault", b =>
                {
                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("KnowledgeId", "VaultId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VaultId");

                    b.ToTable("KnowledgeVaults");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId", "VersionNumber")
                        .IsUnique();

                    b.HasIndex("TenantId", "KnowledgeId");

                    b.ToTable("KnowledgeVersions");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.PortableArchive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityType");

                    b.HasIndex("TenantId", "OriginalId");

                    b.ToTable("PortableArchives");
                });

            modelBuilder.Entity("Knowz.Core.Entities.SystemConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EncryptedValue")
                        .HasColumnType("text");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Knowz.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OAuthEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OAuthSubjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasFilter("\"ApiKey\" IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("TenantId", "Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentVaultId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformData")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VaultType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentVaultId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultAncestor", b =>
                {
                    b.Property<Guid>("AncestorVaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DescendantVaultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.HasKey("AncestorVaultId", "DescendantVaultId");

                    b.HasIndex("DescendantVaultId");

                    b.ToTable("VaultAncestors");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultPerson", b =>
                {
                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VaultId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("VaultPersons");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.EnrichmentActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "KnowledgeId");

                    b.HasIndex("TenantId", "StartedAt");

                    b.ToTable("EnrichmentActivityLogs");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.EnrichmentOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AiProcessingAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedProcessingAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeId");

                    b.HasIndex("Status", "NextRetryAt");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("EnrichmentOutbox");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.PlatformConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyLast4")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ApiKeyProtected")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastTestError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("LastTestStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlatformApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RemoteTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("PlatformConnections");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.PlatformSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("KnowledgeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Operation")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VaultSyncLinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PlatformSyncRuns_TenantId_InProgress")
                        .HasFilter("\"CompletedAt\" IS NULL");

                    b.HasIndex("VaultSyncLinkId")
                        .HasDatabaseName("IX_PlatformSyncRuns_VaultSyncLinkId");

                    b.HasIndex("TenantId", "StartedAt")
                        .HasDatabaseName("IX_PlatformSyncRuns_TenantId_StartedAt");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_PlatformSyncRuns_TenantId_Status");

                    b.ToTable("PlatformSyncRuns");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemSeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MergeStrategy")
                        .HasColumnType("integer");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PromptKey")
                        .HasDatabaseName("IX_PromptTemplates_TenantId_PromptKey");

                    b.HasIndex("UserId", "PromptKey")
                        .HasDatabaseName("IX_PromptTemplates_UserId_PromptKey");

                    b.HasIndex("PromptKey", "Scope", "TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PromptTemplates_Key_Scope_Tenant_User")
                        .HasFilter("\"TenantId\" IS NOT NULL AND \"UserId\" IS NOT NULL");

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.SyncTombstone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LocalEntityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Propagated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PropagatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RemoteEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultSyncLinkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VaultSyncLinkId", "Propagated");

                    b.HasIndex("VaultSyncLinkId", "EntityType", "LocalEntityId");

                    b.ToTable("SyncTombstones");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPermissions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreateVaults")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAllVaultsAccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZonePreference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserTenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserTenantMemberships");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserVaultAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManage")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanWrite")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VaultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("VaultId");

                    b.HasIndex("UserId", "VaultId")
                        .IsUnique();

                    b.ToTable("UserVaultAccess");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.VaultSyncLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPullCursor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastPushCursor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("LastSyncStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("LocalVaultId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlatformApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PlatformConnectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RemoteTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RemoteVaultId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocalVaultId")
                        .IsUnique();

                    b.HasIndex("PlatformConnectionId");

                    b.ToTable("VaultSyncLinks");
                });

            modelBuilder.Entity("KnowledgeTags", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Knowz.Core.Entities.ContentChunk", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany()
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");
                });

            modelBuilder.Entity("Knowz.Core.Entities.FileAttachment", b =>
                {
                    b.HasOne("Knowz.Core.Entities.KnowledgeComment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Knowz.Core.Entities.FileRecord", "FileRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("FileRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany()
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Comment");

                    b.Navigation("FileRecord");

                    b.Navigation("Knowledge");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Topic", "Topic")
                        .WithMany("KnowledgeItems")
                        .HasForeignKey("TopicId");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeComment", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("Comments")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.KnowledgeComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Knowledge");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeEvent", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Event", "Event")
                        .WithMany("KnowledgeEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeEvents")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Knowledge");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeLocation", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeLocations")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Location", "Location")
                        .WithMany("KnowledgeLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgePerson", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgePersons")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Person", "Person")
                        .WithMany("KnowledgePersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeRelationship", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "SourceKnowledge")
                        .WithMany("OutgoingRelationships")
                        .HasForeignKey("SourceKnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Knowledge", "TargetKnowledge")
                        .WithMany("IncomingRelationships")
                        .HasForeignKey("TargetKnowledgeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceKnowledge");

                    b.Navigation("TargetKnowledge");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeVault", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Knowledge", "Knowledge")
                        .WithMany("KnowledgeVaults")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "Vault")
                        .WithMany("KnowledgeVaults")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knowledge");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.User", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Vault", "ParentVault")
                        .WithMany("Children")
                        .HasForeignKey("ParentVaultId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentVault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultAncestor", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Vault", "AncestorVault")
                        .WithMany("Descendants")
                        .HasForeignKey("AncestorVaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "DescendantVault")
                        .WithMany("Ancestors")
                        .HasForeignKey("DescendantVaultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AncestorVault");

                    b.Navigation("DescendantVault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.VaultPerson", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Person", "Person")
                        .WithMany("VaultPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "Vault")
                        .WithMany("VaultPersons")
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.SyncTombstone", b =>
                {
                    b.HasOne("Knowz.SelfHosted.Infrastructure.Data.Entities.VaultSyncLink", "VaultSyncLink")
                        .WithMany()
                        .HasForeignKey("VaultSyncLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultSyncLink");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPermissions", b =>
                {
                    b.HasOne("Knowz.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPermissions", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPreference", b =>
                {
                    b.HasOne("Knowz.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Knowz.SelfHosted.Infrastructure.Data.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserTenantMembership", b =>
                {
                    b.HasOne("Knowz.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Knowz.SelfHosted.Infrastructure.Data.Entities.UserVaultAccess", b =>
                {
                    b.HasOne("Knowz.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Knowz.Core.Entities.Vault", "Vault")
                        .WithMany()
                        .HasForeignKey("VaultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vault");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Event", b =>
                {
                    b.Navigation("KnowledgeEvents");
                });

            modelBuilder.Entity("Knowz.Core.Entities.FileRecord", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Knowledge", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IncomingRelationships");

                    b.Navigation("KnowledgeEvents");

                    b.Navigation("KnowledgeLocations");

                    b.Navigation("KnowledgePersons");

                    b.Navigation("KnowledgeVaults");

                    b.Navigation("OutgoingRelationships");
                });

            modelBuilder.Entity("Knowz.Core.Entities.KnowledgeComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Location", b =>
                {
                    b.Navigation("KnowledgeLocations");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Person", b =>
                {
                    b.Navigation("KnowledgePersons");

                    b.Navigation("VaultPersons");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Topic", b =>
                {
                    b.Navigation("KnowledgeItems");
                });

            modelBuilder.Entity("Knowz.Core.Entities.Vault", b =>
                {
                    b.Navigation("Ancestors");

                    b.Navigation("Children");

                    b.Navigation("Descendants");

                    b.Navigation("KnowledgeVaults");

                    b.Navigation("VaultPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
