using System.ComponentModel.DataAnnotations;
using Knowz.Core.Enums;

namespace Knowz.Core.Entities;

/// <summary>
/// Represents a user in the self-hosted deployment.
/// NOT scoped by ISelfHostedEntity query filters - this is an admin-level entity.
/// </summary>
public class User
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid TenantId { get; set; }

    [Required]
    [MaxLength(100)]
    public string Username { get; set; } = string.Empty;

    [MaxLength(255)]
    public string? Email { get; set; }

    [MaxLength(200)]
    public string? DisplayName { get; set; }

    [Required]
    public string PasswordHash { get; set; } = string.Empty;

    [MaxLength(100)]
    public string? ApiKey { get; set; }

    public UserRole Role { get; set; } = UserRole.User;

    public bool IsActive { get; set; } = true;

    /// <summary>
    /// True only for a first-boot administrator whose password was generated by
    /// the local installer. The API constrains that session until it is changed.
    /// </summary>
    public bool MustChangePassword { get; set; }

    // OAuth fields for future use
    [MaxLength(50)]
    public string? OAuthProvider { get; set; }

    [MaxLength(255)]
    public string? OAuthSubjectId { get; set; }

    [MaxLength(255)]
    public string? OAuthEmail { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? LastLoginAt { get; set; }

    // Navigation
    public virtual Tenant Tenant { get; set; } = null!;
}
